task :default => [:js, :html, :css, :tsc]

coffees = FileList.new("**/*.coffee").exclude(/^bower_components/)
hamls = FileList.new("**/*.haml").exclude(/^bower_components/)
sass = FileList.new("**/*.sass").exclude(/^bower_components/)


task :js   => coffees.ext(".js")
task :html => hamls.ext(".html")
task :css  => sass.ext(".css")


rule '.js' => '.coffee' do |t|
  sh "coffee -c #{t.source}"
end

rule '.html' => '.haml' do |t|
  sh "haml --no-escape-attrs #{t.source} #{t.name}"
end

rule '.css' => '.sass' do |t|
  sh "sass --sourcemap=none -r compass `compass imports` #{t.source}:#{t.name}"
end



# define a task for compiling typescript files

tscs = FileList.new("**/*.ts").exclude(/^bower_components/)
tsc_out = "js/app.js"

task :tsc => tsc_out

file tsc_out => tscs do
  sh "tsc --out #{tsc_out} js/_all.ts"
end
